name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
            tests
            .github
            pyproject.toml
            poetry.lock
            .pre-commit-config.yaml
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files